#!/usr/bin/env bash
#This script shows a really clunky clock
hour=0
minute=1
while ((hour < 13))
do
    echo Hour: $hour
    while ((minute < 60))
    do
       echo $minute
       minute=$((minute + 1))
    done
    hour=$((hour + 1))
    minute=1
done
